### ISSUE TITLE
ncm details 'RangeError: Invalid count value'

### ISSUE THREAD

**Issue by Fishrock123** [nodesource/ncm-cli#105]
From `ncm details depd @ 1.1.2`

```
Module Risk:

...

RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at moduleRisks.forEach (/Users/Jeremiah/npm/lib/node_modules/ncm-cli/lib/report/module.js:126:42)
    at Array.forEach (<anonymous>)
    at moduleReport (/Users/Jeremiah/npm/lib/node_modules/ncm-cli/lib/report/module.js:109:17)
    at Object.details (/Users/Jeremiah/npm/lib/node_modules/ncm-cli/commands/details.js:137:3)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by Jazneil** [comment]
Hey @Fishrock123 can you please estimate this issue?
